# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Create a VCN in Oracle Cloud Infrastructure including default route table, DHCP options and subnets"
stackDescription: ${Messages.solutionsHub.solutions.defaultVCN.stackDescription()}
schemaVersion: 1.1.0
version: "20200301"
locale: "en"

variableGroups:
- title: ${Messages.solutionsHub.generalConfig()}
  visible: false
  variables:
  - compartment_ocid
  - tenancy_ocid
  - region

- title: ${Messages.solutionsHub.requiredConfig()}
  visible: true  
  variables:
  - vcn_display_name

- title: ${Messages.solutionsHub.optionalConfig()}
  visible: true  
  variables:
  - vcn_cidr
  - subnet_dns_label
  - vcn_dns_label

variables:

  compartment_ocid:
    type: oci:identity:compartment:id
    # type: string
    required: true
    title: ${Messages.solutionsHub.genericVariables.compartment.title()}
    description: ${Messages.solutionsHub.genericVariables.compartment.description()}

  region:
    type: oci:identity:region:name
    required: true
    title: ${Messages.solutionsHub.genericVariables.region.title()}
    description: ${Messages.solutionsHub.genericVariables.region.description()}

  vcn_display_name:
    type: string
    required: true
    title: ${Messages.solutionsHub.solutions.defaultVCN.variables.vcn_display_name.title()}
    description: ${Messages.solutionsHub.solutions.defaultVCN.variables.vcn_display_name.description()}

  vcn_cidr:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: ${Messages.solutionsHub.solutions.defaultVCN.variables.vcn_cidr.title()}
    description: ${Messages.solutionsHub.solutions.defaultVCN.variables.vcn_cidr.description()}

  vcn_dns_label:
    type: string
    required: false
    pattern: "^[a-zA-Z][a-zA-Z0-9]{0,14}$"
    title: ${Messages.solutionsHub.solutions.defaultVCN.variables.vcn_dns_label.title()}
    description: ${Messages.solutionsHub.solutions.defaultVCN.variables.vcn_dns_label.description()}

  subnet_dns_label:
    type: string
    required: false
    pattern: "^[a-zA-Z][a-zA-Z0-9]{0,14}$"
    title: ${Messages.solutionsHub.solutions.defaultVCN.variables.subnet_dns_label.title()}
    description: ${Messages.solutionsHub.solutions.defaultVCN.variables.subnet_dns_label.description()}
